// <auto-generated>
//     This code was generated by a CodeHammer
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>

namespace Logging.Log4Net
{
    using log4net;
    using log4net.Config;
    using Logging.Log4Net;
    using System;

    /// <summary>
    /// this class Logger
    /// </summary>
    public class Logger <INTERFACE>
    {
        /// <summary>
        /// The log
        /// </summary>
        private static ILog log = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="Logger"/> class.
        /// </summary>
        public Logger()
        {
            XmlConfigurator.Configure();
            log4net.GlobalContext.Properties["Service"] = Environment.MachineName;
        }

        public void LogError(Type type, string info, Exception ex)
        {
            log = log4net.LogManager.GetLogger(type);
            log.Error(info, ex);
        }
    }
}