// <auto-generated>");
//     This code was generated by a CodeHammer");
//     Changes to this file may cause incorrect behavior and will be lost if");
//     the code is regenerated");
// </auto-generated>");


namespace DatabaseManagerArea
{
    using System;
    using System.Configuration;
    using System.Data.SqlClient;

    public class CodeHammerDatabaseManager
    {
        public static readonly CodeHammerDatabaseManager ClassInstance = new CodeHammerDatabaseManager();

        /// <summary>
        /// Prevents a default instance of the <see cref="CodeHammerDatabaseManager"/> class from being created.
        /// </summary>
        private CodeHammerDatabaseManager()
        {
        }

        /// <summary>
        /// Gets the instance.
        /// </summary>
        /// <value>
        /// The instance.
        /// </value>
        public static CodeHammerDatabaseManager Instance
        {
            get
            {
                return ClassInstance;
            }
        }

        /// <summary>
        /// Inits the database connection.
        /// </summary>
        /// <param name="sqlConn">The SQL conn.</param>
        /// <param name="error">The error.</param>
        /// <returns>return true if success</returns>
        public bool InitDatabaseConnection(out SqlConnection sqlConn, out string error)
        {
            error = string.Empty;
            sqlConn = null;

            try
            {
                sqlConn = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString());
            }
            catch (Exception ex)
            {
                error = ex.StackTrace;
                return false;
            }

            return true;
        }
    }
}