// <auto-generated>");
//     This code was generated by a CodeHammer");
//     Changes to this file may cause incorrect behavior and will be lost if");
//     the code is regenerated");
// </auto-generated>");


namespace DataAccessManagerArea
{
    using System;
    using System.Data;

    /// <summary>
    /// This class CodeHammerDataAccessManager
    /// </summary>
    public static class CodeHammerDataAccessManager
    {
        /// <summary>
        /// Determines whether the specified r has column.
        /// </summary>
        /// <param name="r">The r.</param>
        /// <param name="columnName">Name of the column.</param>
        /// <returns>
        ///   <c>true</c> if the specified r has column; otherwise, <c>false</c>.
        /// </returns>
        public static bool HasColumn(this IDataRecord r, string columnName)
        {
            try
            {
                return r.GetOrdinal(columnName) >= 0;
            }
            catch (IndexOutOfRangeException)
            {
                return false;
            }
        }

        /// <summary>
        /// The dt
        /// </summary>
        public static DataTable dt;
    }
}