// <auto-generated>");
//     This code was generated by a CodeHammer");
//     Changes to this file may cause incorrect behavior and will be lost if");
//     the code is regenerated");
// </auto-generated>");

namespace ServiceHost
{
    using System;
    using System.ServiceModel.Activation;
    using System.Web.Routing;<USINGCASTLEWCF><LOG4NET>
    using Data.Infrastructure;
    using Business;
    using Data;
    using ServiceLibrary;

    /// <summary>
    /// this class Global
    /// </summary>
    public class Global : System.Web.HttpApplication
    {
         <INITCASTLEWCF>

        /// <summary>
        /// Handles the End event of the Application control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="EventArgs" /> instance containing the event data.</param>
        protected void Application_End(object sender, EventArgs e)
        {
            <NEWINITCASTLE>
        }

        /// <summary>
        /// Handles the Start event of the Application control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="EventArgs" /> instance containing the event data.</param>
        private void Application_Start(object sender, EventArgs e)
        {
            <REGISTERWINDSORCONTAINER>
            RouteConfig.RegisterRoutes();
        }

        <REGISTERWINDSORCONTAINERFUNCTION>

    }
}