// <auto-generated>
//     This code was generated by a CodeHammer.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace ServiceHost
{
    <CASTLE>
    using System.ServiceModel.Activation;
    using System.Web.Routing;

    /// <summary>
    /// this class RouteConfig
    /// </summary>
    public class RouteConfig
    {
        /// <summary>
        /// Register rest routes.
        /// </summary>
        public static void RegisterRoutes()
        {
            <REGISTERROUTES>
        }
    }
}